### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by btribouillet** [dunglas/mercure#244]
Hi,

I'm using a Heroku app where I did deploy the Mercure binary i386.

**Version**
v0.8.1

**Buildstack**
https://github.com/ph3nx/heroku-binary-buildpack

**Procfile**
```
web: JWT_KEY=$JWT_KEY ADDR=":$PORT" ALLOW_ANONYMOUS=1 CORS_ALLOWED_ORIGINS=$CORS_ALLOWED_ORIGINS DEBUG=1 ./mercure
```

I don't have any issues when subscribing with the event source.
However, on publish, this error is thrown and the app crashes. (It seems to be a similar issue with #221 )

> runtime error: invalid memory address or nil pointer dereference

The app publishing the event is built with Symfony and env variables are set this way

```
MERCURE_PUBLISH_URL=https://vmm-mercure-staging.herokuapp.com/.well-known/mercure
MERCURE_JWT_TOKEN=eyJhbGci[...]p-f_FwwOim0
```

With a simple test 

```
    /**
     * @Route("/test/mercure", name="test_mercure")
     *
     * @param PublisherInterface $publisher
     * @return Response
     */
    public function test_mercure(PublisherInterface $publisher): Response
    {
        $update = new Update(
            'http://example.com/books/1',
            (string) json_encode(['status' => 'OutOfStock'])
        );

        // The Publisher service is an invokable object
        $publisher($update);

        return new Response('<html><head></head><body>Test Mercure</body></html>');
    }
```

Here the full log

```
2020-03-04T16:18:29.049003+00:00 app[web.1]: time="2020-03-04T16:18:29Z" level=info msg="runtime error: invalid memory address or nil pointer dereference"
2020-03-04T16:18:29.049207+00:00 app[web.1]: goroutine 36 [running]:
2020-03-04T16:18:29.049208+00:00 app[web.1]: runtime/debug.Stack(0x8142f42, 0x90edbe8, 0x85b97a0)
2020-03-04T16:18:29.049208+00:00 app[web.1]: /home/travis/.gimme/versions/go1.13.linux.amd64/src/runtime/debug/stack.go:24 +0x83
2020-03-04T16:18:29.049208+00:00 app[web.1]: runtime/debug.PrintStack()
2020-03-04T16:18:29.049209+00:00 app[web.1]: /home/travis/.gimme/versions/go1.13.linux.amd64/src/runtime/debug/stack.go:16 +0x1a
2020-03-04T16:18:29.049209+00:00 app[web.1]: github.com/gorilla/handlers.recoveryHandler.log(0x868f360, 0x90f2760, 0x868e5a0, 0x90edbc0, 0x1, 0x9102310, 0x1, 0x1)
2020-03-04T16:18:29.049209+00:00 app[web.1]: /home/travis/gopath/pkg/mod/github.com/gorilla/handlers@v1.4.2/recovery.go:89 +0x53
2020-03-04T16:18:29.049210+00:00 app[web.1]: github.com/gorilla/handlers.recoveryHandler.ServeHTTP.func1(0x8693f40, 0x9154000, 0x868f360, 0x90f2760, 0x868e5a0, 0x90edbc0, 0x1)
2020-03-04T16:18:29.049210+00:00 app[web.1]: /home/travis/gopath/pkg/mod/github.com/gorilla/handlers@v1.4.2/recovery.go:74 +0xa2
2020-03-04T16:18:29.049210+00:00 app[web.1]: panic(0x8551360, 0x8a15b00)
2020-03-04T16:18:29.049211+00:00 app[web.1]: /home/travis/.gimme/versions/go1.13.linux.amd64/src/runtime/panic.go:679 +0x16b
2020-03-04T16:18:29.049211+00:00 app[web.1]: runtime/internal/atomic.Store64(0x909eb7c, 0x1, 0x0)
2020-03-04T16:18:29.049211+00:00 app[web.1]: /home/travis/.gimme/versions/go1.13.linux.amd64/src/runtime/internal/atomic/asm_386.s:205 +0xb
2020-03-04T16:18:29.049212+00:00 app[web.1]: go.uber.org/atomic.(*Uint64).Store(...)
2020-03-04T16:18:29.049212+00:00 app[web.1]: /home/travis/gopath/pkg/mod/go.uber.org/atomic@v1.5.1/atomic.go:215
2020-03-04T16:18:29.049212+00:00 app[web.1]: github.com/dunglas/mercure/hub.(*BoltTransport).persist.func1(0x914a300, 0x804cc01, 0x914a300)
2020-03-04T16:18:29.049213+00:00 app[web.1]: /home/travis/gopath/src/github.com/dunglas/mercure/hub/bolt_transport.go:124 +0x11c
2020-03-04T16:18:29.049213+00:00 app[web.1]: go.etcd.io/bbolt.(*DB).Update(0x90c2140, 0x91617c8, 0x0, 0x0)
2020-03-04T16:18:29.049213+00:00 app[web.1]: /home/travis/gopath/pkg/mod/go.etcd.io/bbolt@v1.3.3/db.go:694 +0x8b
2020-03-04T16:18:29.049213+00:00 app[web.1]: github.com/dunglas/mercure/hub.(*BoltTransport).persist(0x909eb40, 0x9142120, 0x9078100, 0x808912b)
2020-03-04T16:18:29.049213+00:00 app[web.1]: /home/travis/gopath/src/github.com/dunglas/mercure/hub/bolt_transport.go:109 +0x5a
2020-03-04T16:18:29.049214+00:00 app[web.1]: github.com/dunglas/mercure/hub.(*BoltTransport).Write(0x909eb40, 0x9142120, 0x1c755ab8, 0xc0ad4ba)
2020-03-04T16:18:29.049214+00:00 app[web.1]: /home/travis/gopath/src/github.com/dunglas/mercure/hub/bolt_transport.go:84 +0x5d
2020-03-04T16:18:29.049214+00:00 app[web.1]: github.com/dunglas/mercure/hub.(*Hub).dispatch(0x909c6c0, 0x9142120, 0x85c0427, 0x4)
2020-03-04T16:18:29.049215+00:00 app[web.1]: /home/travis/gopath/src/github.com/dunglas/mercure/hub/publish.go:17 +0x3a
2020-03-04T16:18:29.049215+00:00 app[web.1]: github.com/dunglas/mercure/hub.(*Hub).PublishHandler(0x909c6c0, 0xe7349050, 0x91043c0, 0x914a280)
2020-03-04T16:18:29.049215+00:00 app[web.1]: /home/travis/gopath/src/github.com/dunglas/mercure/hub/publish.go:76 +0x68b
2020-03-04T16:18:29.049215+00:00 app[web.1]: net/http.HandlerFunc.ServeHTTP(0x9076da8, 0xe7349050, 0x91043c0, 0x914a280)
2020-03-04T16:18:29.049215+00:00 app[web.1]: /home/travis/.gimme/versions/go1.13.linux.amd64/src/net/http/server.go:2007 +0x34
2020-03-04T16:18:29.049216+00:00 app[web.1]: github.com/gorilla/mux.(*Router).ServeHTTP(0x90acea0, 0xe7349050, 0x91043c0, 0x914a100)
2020-03-04T16:18:29.049216+00:00 app[web.1]: /home/travis/gopath/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212 +0xbb
2020-03-04T16:18:29.049216+00:00 app[web.1]: github.com/gorilla/handlers.(*cors).ServeHTTP(0x909ecd0, 0xe7349050, 0x91043c0, 0x914a100)
2020-03-04T16:18:29.049216+00:00 app[web.1]: /home/travis/gopath/pkg/mod/github.com/gorilla/handlers@v1.4.2/cors.go:54 +0xccc
2020-03-04T16:18:29.049216+00:00 app[web.1]: github.com/unrolled/secure.(*Secure).Handler.func1(0xe7349050, 0x91043c0, 0x914a100)
2020-03-04T16:18:29.049216+00:00 app[web.1]: /home/travis/gopath/pkg/mod/github.com/unrolled/secure@v1.0.7/secure.go:177 +0xaa
2020-03-04T16:18:29.049217+00:00 app[web.1]: net/http.HandlerFunc.ServeHTTP(0x9082590, 0xe7349050, 0x91043c0, 0x914a100)
2020-03-04T16:18:29.049217+00:00 app[web.1]: /home/travis/.gimme/versions/go1.13.linux.amd64/src/net/http/server.go:2007 +0x34
2020-03-04T16:18:29.049217+00:00 app[web.1]: github.com/gorilla/handlers.loggingHandler.ServeHTTP(0x868eda0, 0x90760e0, 0x868f6c0, 0x9082590, 0x85e9da0, 0x8693f40, 0x9154000, 0x914a100)
2020-03-04T16:18:29.049217+00:00 app[web.1]: /home/travis/gopath/pkg/mod/github.com/gorilla/handlers@v1.4.2/logging.go:45 +0x1cc
2020-03-04T16:18:29.049218+00:00 app[web.1]: github.com/gorilla/handlers.recoveryHandler.ServeHTTP(0x868f360, 0x90f2760, 0x868e5a0, 0x90edbc0, 0x1, 0x8693f40, 0x9154000, 0x914a100)
2020-03-04T16:18:29.049218+00:00 app[web.1]: /home/travis/gopath/pkg/mod/github.com/gorilla/handlers@v1.4.2/recovery.go:78 +0x7c
2020-03-04T16:18:29.049218+00:00 app[web.1]: net/http.serverHandler.ServeHTTP(0x9089830, 0x8693f40, 0x9154000, 0x914a100)
2020-03-04T16:18:29.049218+00:00 app[web.1]: /home/travis/.gimme/versions/go1.13.linux.amd64/src/net/http/server.go:2802 +0x84
2020-03-04T16:18:29.049218+00:00 app[web.1]: net/http.(*conn).serve(0x91400c0, 0x8694960, 0x91042a0)
2020-03-04T16:18:29.049218+00:00 app[web.1]: /home/travis/.gimme/versions/go1.13.linux.amd64/src/net/http/server.go:1890 +0x7ad
2020-03-04T16:18:29.049219+00:00 app[web.1]: created by net/http.(*Server).Serve
2020-03-04T16:18:29.049219+00:00 app[web.1]: /home/travis/.gimme/versions/go1.13.linux.amd64/src/net/http/server.go:2927 +0x311
```

**Comment by btribouillet** [comment]
The issue was not using the correct binary. While other binaries would throw "cannot execute binary file: Exec format error" the i386 binary was not triggering the same error.

I changed the binary to the x86_64 and it's all working as intended.
