### ISSUE TITLE
Helm chart does yeld an accessible server

### ISSUE THREAD

**Issue by blackheaven** [dunglas/mercure#600]
## Problem description

When I try to use Mercure inside Kubernetes via Helm chart, I can't connect to the server.

## Versions

 * Mercure: 0.13.0
 * Minikube: 1.24.0

## Steps to reproduce

* Start the server

```
$ minikube start
$ helm install --set subscriberJwtKey=SECRET demo mercure/mercure
```

* Open the port

```
$ export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=mercure,app.kubernetes.io/instance=hetchr-mercure" -o jsonpath="{.items[0].metadata.name}")
$ export CONTAINER_PORT=$(kubectl get pod --namespace default $POD_NAME -o jsonpath="{.spec.containers[0].ports[0].containerPort}")
$ echo "Visit http://127.0.0.1:8081 to use your application"
$ kubectl --namespace default port-forward $POD_NAME 8080:$CONTAINER_PORT
```

 * Try to connect to it

```
from sseclient import SSEClient
import jwt

token = jwt.encode(
    {'mercure': {'subscribe': ['*']}},
    'SECRET',
    algorithm='HS256',
)

updates = SSEClient(
    'http://localhost:8080/.well-known/mercure',
    params={'topic': ['*']},
    headers={'Authorization': 'Bearer '+token},
)
for update in updates:
    print("Update received: ", update)
```

## Actual behaviour

Here's what I get:

```
Traceback (most recent call last):
  File "/tmp/python.py", line 10, in <module>
    updates = SSEClient(
  File "/nix/store/0ry016qm8v43bsqh2hz1a18wn04p7mw5-python3-3.9.6-env/lib/python3.9/site-packages/sseclient.py", line 48, in __init__
    self._connect()
  File "/nix/store/0ry016qm8v43bsqh2hz1a18wn04p7mw5-python3-3.9.6-env/lib/python3.9/site-packages/sseclient.py", line 63, in _connect
    self.resp.raise_for_status()
  File "/nix/store/0ry016qm8v43bsqh2hz1a18wn04p7mw5-python3-3.9.6-env/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: http://localhost:8080/.well-known/mercure?topic=%2A
```

## Additional information

It fails with any topic.

If works when I launch it directly through `docker` in standalone.

**Comment by dunglas** [comment]
What was the issue @blackheaven?

**Comment by blackheaven** [comment]
Actually, I don't know, I've tried again with a fresh minikube and it worked.

But I still have the issue with RS256 keys.
