### ISSUE TITLE
DNS issues with Alpine

### ISSUE THREAD

**Issue by B-Galati** [dunglas/mercure#754]
Hello,

I recently had network issue trying to reach Mercure Hub at my company. It's very random and rare and only happen with Mercure. 

Today, I stumbled upon this article which talks about issue with Alpine based container; and some are related to DNS issues: https://betterprogramming.pub/why-i-will-never-use-alpine-linux-ever-again-a324fd0cbfd6

So maybe:
- Either add another image name based on something else than Alpine?
- Or update the current base image?

Or don't do anything for some reasons :+1: 

FYI the network issue I had was the following, that does not look like a DNS issue but well, that may be something else related to Alpine, IDK.

```
Symfony\Component\HttpClient\Exception\TransportException: Empty reply from server for "http://mercure-hub.cluster.local/.well-known/mercure".

#26 /vendor/symfony/http-client/Chunk/ErrorChunk.php(53): Symfony\Component\HttpClient\Chunk\ErrorChunk::isTimeout
#25 /vendor/symfony/http-client/Response/AsyncResponse.php(67): Symfony\Component\HttpClient\Response\AsyncResponse::Symfony\Component\HttpClient\Response\{closure}
#24 /vendor/symfony/http-client/Response/CommonResponseTrait.php(152): Symfony\Component\HttpClient\Response\AsyncResponse::initialize
#23 /vendor/symfony/http-client/Response/CommonResponseTrait.php(44): Symfony\Component\HttpClient\Response\AsyncResponse::getContent
#22 /vendor/symfony/mercure/src/Hub.php(105): Symfony\Component\Mercure\Hub::publish
.....
#16 /vendor/symfony/messenger/Middleware/FailedMessageProcessingMiddleware.php(34): Symfony\Component\Messenger\Middleware\FailedMessageProcessingMiddleware::handle
#15 /vendor/symfony/messenger/Middleware/DispatchAfterCurrentBusMiddleware.php(68): Symfony\Component\Messenger\Middleware\DispatchAfterCurrentBusMiddleware::handle
#14 /vendor/symfony/messenger/Middleware/RejectRedeliveredMessageMiddleware.php(48): Symfony\Component\Messenger\Middleware\RejectRedeliveredMessageMiddleware::handle
#13 /vendor/symfony/messenger/Middleware/AddBusNameStampMiddleware.php(37): Symfony\Component\Messenger\Middleware\AddBusNameStampMiddleware::handle
#12 /vendor/symfony/messenger/MessageBus.php(77): Symfony\Component\Messenger\MessageBus::dispatch
#11 /vendor/symfony/messenger/HandleTrait.php(43): Infrastructure\Bus\Symfony\Messenger\Bus\AbstractBus::handleMessage
....
#6 /vendor/symfony/http-kernel/HttpKernel.php(163): Symfony\Component\HttpKernel\HttpKernel::handleRaw
#5 /vendor/symfony/http-kernel/HttpKernel.php(75): Symfony\Component\HttpKernel\HttpKernel::handle
#4 /vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\Kernel::handle
#2 /vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php(35): Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner::run
#1 /vendor/autoload_runtime.php(35): require_once
#0 /public/index.php(5): null
```

**Comment by B-Galati** [comment]
Would be nice to reopen or have an answer 🙏
