### ISSUE TITLE
No Documetation for installation with CaddyServer

### ISSUE THREAD

**Issue by B9M** [dunglas/mercure#783]
No Documentation for installing mercure with caddy as mentioned on documentation in lunix version , I have this error : 

> 2023/06/16 02:09:30 invalid config: one of "jwt_key" or "publisher_jwt_key" configuration parameter must be defined
panic: invalid config: one of "jwt_key" or "publisher_jwt_key" configuration parameter must be defined
goroutine 1 [running]:
log.Panic({0xc0001e9cd0?, 0x0?, 0x0?})
/opt/hostedtoolcache/go/1.20.4/x64/src/log/log.go:384 +0x65
github.com/dunglas/mercure.NewHubFromViper(0xc000184d00)
	/home/runner/work/mercure/mercure/config.go:135 +0x6f
github.com/dunglas/mercure.Start()
	/home/runner/work/mercure/mercure/config.go:251 +0x35
github.com/dunglas/mercure/cmd.glob..func1(0x10c3b60?, {0xb64232?, 0x3?, 0x3?})
	/home/runner/work/mercure/mercure/cmd/root.go:23 +0x17
github.com/spf13/cobra.(*Command).execute(0x10c3b60, {0xc000186050, 0x3, 0x3})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x10c3b60)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/dunglas/mercure/cmd.Execute()
	/home/runner/work/mercure/mercure/cmd/root.go:29 +0x25
main.main()
	/home/runner/work/mercure/mercure/cmd/mercure/main.go:6 +0x17

**Comment by B9M** [comment]
i was using the legacy version  **mercure-legacy_0.14.10_Linux_x86_64.tar.gz**   , without the  version  **mercure_0.14.10_Linux_x86_64.tar.gz**  it works fine 

> sudo SERVER_NAME=:3000  MERCURE_PUBLISHER_JWT_KEY='!ChangeThisMercureHubJWTSecretKey!' MERCURE_SUBSCRIBER_JWT_KEY='!ChangeThisMercureHubJWTSecretKey!' ./mercure run --config Caddyfile.dev
