### ISSUE TITLE
Segfault on mercure 0.14

### ISSUE THREAD

**Issue by SGaulard** [dunglas/mercure#785]
Hello All,

We have some random segfault on our mercure. I don't know if we miss something in our config, but everything seem to be working as expected.
It look like a bug to me. Here is our environment: 

Docker:
```
	Server:
	 Engine:
	  Version:          20.10.21
	  API version:      1.41 (minimum version 1.12)
	  Go version:       go1.18.1
	  Git commit:       20.10.21-0ubuntu1~20.04.2
	  Built:            Thu Apr 27 05:37:01 2023
	  OS/Arch:          linux/amd64
	  Experimental:     false
	 containerd:
	  Version:          1.6.12-0ubuntu1~20.04.1
	  GitCommit:        
	 runc:
	  Version:          1.1.4-0ubuntu1~20.04.3
	  GitCommit:        
	 docker-init:
	  Version:          0.19.0
	  GitCommit:

```

image: `dunglas/mercure:v0.14`

And the logs:

```
"[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x578198]"
"panic: runtime error: invalid memory address or nil pointer dereference"
"net/http.(*chunkWriter).flush(0x40acad?)"
"bufio.(*Writer).Flush(0xc006e1cc90?)"
"/opt/hostedtoolcache/go/1.20.4/x64/src/bufio/bufio.go:622 +0x18"
"goroutine 15599940 [running]:"
"/opt/hostedtoolcache/go/1.20.4/x64/src/net/http/server.go:402 +0x3f"
"net/http.(*response).FlushError(0xc00231bc00)"
"/opt/hostedtoolcache/go/1.20.4/x64/src/net/http/server.go:1707 +0x55"
"net/http.(*response).Flush(0x40bddd?)"
"/opt/hostedtoolcache/go/1.20.4/x64/src/net/http/server.go:1699 +0x19"
"/home/runner/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/responsewriter.go:51"
"github.com/caddyserver/caddy/v2/modules/caddyhttp.(*ResponseWriterWrapper).Flush(...)"
"github.com/caddyserver/caddy/v2/modules/caddyhttp.(*ResponseWriterWrapper).Flush(...)"
"/home/runner/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/responsewriter.go:51"
"github.com/caddyserver/caddy/v2/modules/caddyhttp/encode.(*responseWriter).Flush(0x7f6f0f525fe0?)"
"/home/runner/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/encode/encode.go:212 +0x27"
"github.com/dunglas/mercure.(*Hub).write.func1()"
"/home/runner/work/mercure/mercure/subscribe.go:211 +0x90"
"created by github.com/dunglas/mercure.(*Hub).write"
"/home/runner/work/mercure/mercure/subscribe.go:209 +0x158"
```

I hope someone can help me with this.  I stay available if you  need more information.
Thanks !

**Comment by dunglas** [comment]
Are you using the latest version of Mercure (try `docker pull`). This looks similar to https://github.com/dunglas/mercure/pull/780

**Comment by SGaulard** [comment]
indeed, we try it and it's seems to be fixed. We will monitor it for a couple of days. Thanks a lot
